### ISSUE TITLE
Set "noreferrer noopener" rel attributes for external links

### ISSUE THREAD

**Issue by jormee** [TejasQ/tejaskumar.com#10]
Hi @TejasQ,
adding a `rel="noreferrer noopener"` attribute to links to external pages helps improve performance and prevents vulnerabilities.

```
/tejaskumar_(twitter.com) | _blank 
/tejasq(github.com) | _blank |  
/TejasQ/tejaskumar.com(github.com) | _blank |  
```

**Comment by TejasQ** [comment]
Hi jormee! Thanks for this! Can you tell me how exactly this attribute helps improve performance and prevents vulnerabilities?

**Comment by jormee** [comment]
Hi Tejas,
When you link to an external site using the `target="blank"` attribute without the `rel="noopener"` attribute, the new tab/window exposes the window object of the current window. see [this post](https://mathiasbynens.github.io/rel-noopener/) for more information.
Also, this [google dev post](https://developers.google.com/web/tools/lighthouse/audits/noopener?utm_source=lighthouse&utm_medium=devtools) talks about the performance effect.

Kind regards

**Comment by TejasQ** [comment]
That's amazing! Thank you so much! Would you like to open a PR that fixes this?

**Comment by jormee** [comment]
Sure, I would love to

**Comment by TejasQ** [comment]
Thanks for the PR!
