### ISSUE TITLE
Set <html lang="en"> for A11y and better audit

### ISSUE THREAD

**Issue by Tuhaj** [TejasQ/tejaskumar.com#6]
It's hard to believe but `_document.js` needs to be added for this.
https://github.com/isaachinman/next-i18next/issues/20#

**Comment by TejasQ** [comment]
Nice! Let's do it!

**Comment by BondoS** [comment]
Is there any specific standard or good practice to write _document.js?

**Comment by TejasQ** [comment]
I don't think there's anything more than https://github.com/zeit/next.js/#custom-document about it tbh but maybe @timneutkens has more insight/resources.

**Comment by TejasQ** [comment]
Added. Thank you!
